ARG  BASE_IMAGE_VERSION=latest
FROM fiware/orion-ld-base:${BASE_IMAGE_VERSION}

ARG PATH_TO_SRC='/opt/orion/'

RUN  apt-get install -y lcov

COPY . ${PATH_TO_SRC}
WORKDIR ${PATH_TO_SRC}

ENTRYPOINT ["docker/build.sh"]
